#!/bin/bash

###############################################################################
# DEFAULT CONFIG
###############################################################################
DEFAULT_SENDMAIL_BIN="/usr/sbin/sendmail"

#~ Mail config define a mail command to receive the reporting
DEFAULT_MAIL_ADDRESS_FROM="no-reply@example.com"
DEFAULT_MAIL_ADDRESS_DISPLAY="Daemon Restart"
DEFAULT_MAIL_SUBJECT="[Monitoring] Daemons - RESTARTING Daemon - `date '+%Y/%m/%d %H:%M:%S'`"

###############################################################################
# SET CONFIG
###############################################################################
SENDMAIL_BIN=${SENDMAIL_BIN:-${DEFAULT_SENDMAIL_BIN}}
MAIL_ADDRESS_FROM=${MAIL_ADDRESS_FROM:-${DEFAULT_MAIL_ADDRESS_FROM}}
MAIL_ADDRESS_DISPLAY=${MAIL_ADDRESS_DISPLAY:-${DEFAULT_MAIL_ADDRESS_DISPLAY}}
MAIL_ADDRESS_TO=${MAIL_ADDRESS_TO:-""}
MAIL_SUBJECT=${MAIL_SUBJECT:-${DEFAULT_MAIL_SUBJECT}}

MAIL_CMD="${SENDMAIL_BIN} -f ${MAIL_ADDRESS_FROM} -F \"${MAIL_ADDRESS_DISPLAY}\" ${MAIL_ADDRESS_TO}"

##
# Check if daemon in list are running
#
# @return string
##
check_daemons() {

    local daemonsList=${1}
    local debugValue="${2}"
    local finalReturn=""

    for daemonToCheck in ${daemonsList[@]}
    do
            read daemonPath statusOption DT <<<$(IFS="|"; echo ${daemonToCheck})

            [ ${debugValue} -ge 4 ] && echo "$0 - `date "+%Y/%m/%d %H:%M:%S"` - DEBUG - daemon: ${daemonPath} // options: ${statusOption}"
            local statusOutput=`${daemonPath} status ${statusOption} 2>&1`
            [ ${debugValue} -ge 4 ] && echo "$0 - `date "+%Y/%m/%d %H:%M:%S"` - DEBUG - status for ${daemonPath}: ${statusOutput}"
            local failOutput=`echo -e "${statusOutput}" | grep -v ' is running'`
            [ ${debugValue} -ge 4 ] && echo "$0 - `date "+%Y/%m/%d %H:%M:%S"` - DEBUG - fail status for ${daemonPath}: ${statusOutput}"
            local restartCommand="${daemonPath} start ${statusOption}"

            if [[ ! -z "${failOutput}" ]]
            then
                    finalReturn="${finalReturn}\tfor ${daemonPath}\n${failOutput} => RESTARTED\n"
                    [ ${debugValue} -ge 4 ] && echo "${restartCommand}"
                    eval ${restartCommand}
            fi

    done

    echo "${finalReturn}"
}

send_mail() {
    local finalReturn="${1}"

    MAIL_CMD="${SENDMAIL_BIN} -f ${MAIL_ADDRESS_FROM} -F \"${MAIL_ADDRESS_DISPLAY}\" ${MAIL_ADDRESS_TO}"
    (echo "Subject: ${MAIL_SUBJECT}"; \
            echo -e "MIME-Version: 1.0\nContent-Type: text/html\n"; \
            echo '<pre>'; \
            echo -e "It seems there is (are) daemon(s) with problem. They have been restarted\n\n"; \
            echo -e "${finalReturn}\n"; \
            echo -e "\n\n"; \
            echo -e "Generated by $0 on `hostname` - `date`"; \
            echo '</pre>') \
    | eval ${MAIL_CMD}
}

